### ISSUE TITLE
Doesn't work in Emacs 24

### ISSUE THREAD

**Issue by kirillk77** [nicferrier/emacs-noflet#10]
Fresh version (08a0932998408746eb14eb5a65149247510173c2) doesn't work in Emacs 24.

error: Required feature `cl-indent' was not provided

**Comment by kirillk77** [comment]
cl-indent doesn't provide anything

**Comment by nicferrier** [comment]
Hum. It's a new 24 thing. Sorry, I didn't test in 24.3. I'll go fix it. Your fix isn't right though.

**Comment by nicferrier** [comment]
bumped the version with a fix. thanks!
