### ISSUE TITLE
flet/let like indentation

### ISSUE THREAD

**Issue by bbatsov** [nicferrier/emacs-noflet#4]
I think it'd great to instruct Emacs to indent `noflet` forms the same way it indents `let/flet`.

```
(declare (indent 1) (debug noflet))
```

**Comment by nicferrier** [comment]
It indents as the extended 'cl definitions for flet, which are nicest imo.

To get that to work you have to have lisp-indent-function setqd to 'common-lisp-indent-function

I'm not sure how to make that better.
