### ISSUE TITLE
Lazy evaluation

### ISSUE THREAD

**Issue by rejeep** [nicferrier/emacs-noflet#5]
Hi,

I have a project where I want a DSL looking like this:

``` lisp
(name "foo")
(execute
 (compile "bar")
 (compile "baz"))
```

Basically I want to read a couple files with this DSL. I want `name` to evaluate directly, but I don't want the `execute` block to. Is there any way for noflet to be lazy in the arguments to `compile` so that I can save the state and evaluate it later? The only way I can think of is:

``` lisp
(name "foo")
(execute
 '(progn (compile "bar")
         (compile "baz")))
```

But that's not as nice.

**Comment by nicferrier** [comment]
Surely you want macrolet for that?

**Comment by rejeep** [comment]
Didn't know about that one, will check it out. Thanks!

Btw, will noflet ever support macros like that?

**Comment by nicferrier** [comment]
I don't think so since macrolet already does it why would you want it to?

**Comment by rejeep** [comment]
Yes, just asking. Thanks!
