### ISSUE TITLE
Tags on Releases

### ISSUE THREAD

**Issue by phillord** [nicferrier/emacs-noflet#9]
Can you add tags to release please, so that it works with MELPA-Stable

**Comment by nicferrier** [comment]
Why don't you pull it from marmalade instead? Now I have to support MELPA because people won't use marmalade?

**Comment by phillord** [comment]
Hmm, yes, I hadn't considered that. Maybe that wasn't that subtle.

I stopped pulling from marmalade a while back because it wasn't very stable, which was giving me during CI. I could try turning it on again, but I don't like having both MELPA and Marmalade on at the same time, because I do not understand how package.el decided which one to get a package from. In this case, though, it should be safe, and I could avoid using MELPA (I like stable me!). Having said all of that, release tags are convienient and useful aside from MELPA-stable.

Actually, at the moment, I don't understand where the dependency on noflet comes from with my package; it used to work, so someones changed something somewhere!

Anyway, I'll close this issue. Nice if you add them, if not I can survive!

**Comment by nicferrier** [comment]
melpa-stable is small compared to marmalade. all the stability issues with marmalade are gone. it's https. what's not to like.

**Comment by phillord** [comment]
As a user? Nothing at all. It's nice. As a developer, also nothing. But, melpa is easier. I push to git, I tag my releases anyway. Everything follows from that. Contributing the recipe is harder for MELPA than the first upload to marmalade (although easier than getting stuff into ELPA).
